# Generated by Django 4.0.4 on 2022-06-07 08:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('modules', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='farmer_reg',
            old_name='phone_number',
            new_name='phone',
        ),
    ]
