# Generated by Django 4.0.4 on 2022-06-11 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modules', '0002_rename_phone_number_farmer_reg_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='kreg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('address', models.TextField()),
                ('phone', models.CharField(max_length=12)),
                ('email', models.EmailField(max_length=255)),
                ('city', models.CharField(max_length=255)),
                ('pincode', models.TextField()),
                ('password1', models.CharField(max_length=255)),
                ('password2', models.CharField(max_length=255)),
            ],
        ),
    ]
