# Generated by Django 4.0.4 on 2022-06-11 07:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('modules', '0003_kreg'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='kreg',
            new_name='krishireg',
        ),
    ]
