# Generated by Django 4.0.4 on 2022-06-13 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modules', '0004_rename_kreg_krishireg'),
    ]

    operations = [
        migrations.AddField(
            model_name='krishireg',
            name='status',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
