# Generated by Django 4.0.4 on 2022-06-14 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modules', '0005_krishireg_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='feed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=255)),
                ('description', models.TextField()),
            ],
        ),
    ]
