# Generated by Django 4.0.4 on 2022-06-17 16:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('modules', '0006_feed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='krishireg',
            name='status',
        ),
    ]
