# Generated by Django 4.0.4 on 2022-06-25 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modules', '0009_solreq'),
    ]

    operations = [
        migrations.CreateModel(
            name='user_login',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50)),
                ('pass1', models.CharField(max_length=50)),
                ('u_type', models.CharField(max_length=50)),
            ],
        ),
    ]
