# Generated by Django 4.0.4 on 2022-06-25 11:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('modules', '0011_userreg'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userreg',
            old_name='password',
            new_name='pass1',
        ),
    ]
