# Generated by Django 4.0.4 on 2022-06-25 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modules', '0012_rename_password_userreg_pass1'),
    ]

    operations = [
        migrations.CreateModel(
            name='farmerreg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('address', models.TextField()),
                ('phone', models.CharField(max_length=12)),
                ('email', models.EmailField(max_length=255)),
                ('place', models.CharField(max_length=255)),
                ('pincode', models.TextField()),
                ('username', models.CharField(max_length=255)),
                ('pass1', models.CharField(max_length=255)),
            ],
        ),
    ]
