# Generated by Django 4.0.4 on 2022-06-25 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modules', '0013_farmerreg'),
    ]

    operations = [
        migrations.AddField(
            model_name='farmerreg',
            name='user_id',
            field=models.IntegerField(null=True),
        ),
    ]
