# Generated by Django 4.0.4 on 2022-06-25 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modules', '0014_farmerreg_user_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='farmerreg1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(null=True)),
                ('name', models.CharField(max_length=255)),
                ('address', models.TextField()),
                ('phone', models.CharField(max_length=12)),
                ('email', models.EmailField(max_length=255)),
                ('place', models.CharField(max_length=255)),
                ('pincode', models.TextField()),
                ('username', models.CharField(max_length=255)),
                ('pass1', models.CharField(max_length=255)),
            ],
        ),
    ]
