# Generated by Django 4.0.4 on 2022-06-25 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modules', '0016_krishireg1_delete_farmerreg1'),
    ]

    operations = [
        migrations.AddField(
            model_name='krishireg1',
            name='username',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
