# Generated by Django 4.0.4 on 2022-07-03 17:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('modules', '0017_krishireg1_username'),
    ]

    operations = [
        migrations.CreateModel(
            name='solreq1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(null=True)),
                ('description', models.TextField()),
                ('dt', models.DateField()),
                ('status', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='farmerrequest1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('name', models.CharField(max_length=255, null=True)),
                ('email', models.EmailField(max_length=255)),
                ('description', models.TextField()),
                ('dt', models.DateField()),
                ('status', models.CharField(max_length=25)),
                ('kid', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='modules.krishireg1')),
            ],
        ),
    ]
