# Generated by Django 4.0.4 on 2022-07-03 19:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('modules', '0018_solreq1_farmerrequest1'),
    ]

    operations = [
        migrations.CreateModel(
            name='krishreply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('description', models.TextField()),
                ('dt', models.DateField()),
                ('status', models.CharField(max_length=25)),
                ('farmer_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='modules.farmerrequest1')),
            ],
        ),
    ]
