# Generated by Django 4.0.4 on 2022-07-04 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modules', '0019_krishreply'),
    ]

    operations = [
        migrations.CreateModel(
            name='krishreply1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('farmer_id', models.IntegerField()),
                ('description', models.TextField()),
                ('dt', models.DateField()),
                ('status', models.CharField(max_length=25)),
            ],
        ),
        migrations.AddField(
            model_name='farmerrequest1',
            name='reply_msg',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
