# Generated by Django 4.0.4 on 2022-07-04 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modules', '0020_krishreply1_farmerrequest1_reply_msg'),
    ]

    operations = [
        migrations.CreateModel(
            name='pfeedback1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(null=True)),
                ('description', models.TextField(null=True)),
                ('reply', models.TextField(null=True)),
                ('dt', models.DateField()),
                ('status', models.BooleanField(default=False)),
            ],
        ),
    ]
